export default [
  {
    id: null,
    class: 'sheet',
    title: null,
    rootTopic: {},
    extensions: [
      {
        provider: 'org.xmind.ui.skeleton.structure.style',
        content: {
          centralTopic: 'org.xmind.ui.map.clockwise',
          mainTopic: 'org.xmind.ui.logic.right',
        },
      },
    ],
    theme: {
      id: '01847e5a-fba1-4725-93c4-df78b7de694a',
      centralTopic: {
        id: 'c5069014-b642-4cf5-bb50-1d29bd0df2a1',
        properties: {
          'line-color': '#232323',
          'shape-class': 'org.xmind.topicShape.ellipserect',
          'line-class': 'org.xmind.branchConnection.curve',
          'line-width': '3pt',
          'line-pattern': 'solid',
          'fill-pattern': 'solid',
          'border-line-width': '3pt',
          'arrow-end-class': 'org.xmind.arrowShape.none',
          'alignment-by-level': 'inactived',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': 600,
          'fo:font-size': '28pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'center',
          'svg:fill': '#bcbcbc',
        },
      },
      mainTopic: {
        id: '70cef26a-bf8a-4a75-a3ba-c39b54a6401d',
        properties: {
          'shape-class': 'org.xmind.topicShape.ellipserect',
          'line-class': 'org.xmind.branchConnection.bight',
          'fill-pattern': 'solid',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': '500',
          'fo:font-size': '18pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'left',
          'border-line-width': '3',
          'line-width': '2pt',
          'svg:fill': '#d6d6d6',
        },
      },
      subTopic: {
        id: 'd5c7d9c0-e954-4c99-9e01-91cccd629c22',
        properties: {
          'shape-class': 'org.xmind.topicShape.underline',
          'line-class': 'org.xmind.branchConnection.bight',
          'fill-pattern': 'solid',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': 'normal',
          'fo:font-size': '14pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'left',
          'svg:fill': 'none',
        },
      },
      summaryTopic: {
        id: 'dc5d147f-2c2a-423f-8d4f-26c6e4cdc4ec',
        properties: {
          'border-line-color': '#a3a3a3',
          'shape-class': 'org.xmind.topicShape.roundedRect',
          'line-class': 'org.xmind.branchConnection.bight',
          'fill-pattern': 'solid',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': 500,
          'fo:font-size': '14pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'left',
          'border-line-width': '0pt',
          'svg:fill': '#a3a3a3',
        },
      },
      calloutTopic: {
        id: 'b2ccd2cb-e4d0-4c1d-8615-fea7a1b98854',
        properties: {
          'svg:fill': '#a3a3a3',
          'border-line-color': '#a3a3a3',
          'callout-shape-class': 'org.xmind.calloutTopicShape.balloon.ellipse',
          'fill-pattern': 'solid',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': 'normal',
          'fo:font-size': '14pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'left',
        },
      },
      floatingTopic: {
        id: '1db99452-2bb0-4de8-87f5-cdeb8a591d7b',
        properties: {
          'border-line-color': '#232323',
          'shape-class': 'org.xmind.topicShape.ellipserect',
          'line-class': 'org.xmind.branchConnection.bight',
          'line-pattern': 'solid',
          'fill-pattern': 'solid',
          'arrow-end-class': 'org.xmind.arrowShape.none',
          'fo:font-family': 'Montserrat',
          'fo:font-style': 'normal',
          'fo:font-weight': 500,
          'fo:font-size': '18pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'left',
          'line-width': '2pt',
          'border-line-width': '3',
          'svg:fill': '#d6d6d6',
        },
      },
      boundary: {
        id: 'beaff7ce-691f-481d-847c-c5f43d125660',
        properties: {
          'svg:fill': '#a3a3a3',
          'line-color': '#a3a3a3',
          'shape-class': 'org.xmind.boundaryShape.roundedRect',
          'shape-corner': '20pt',
          'line-width': '2',
          'line-pattern': 'dash',
          'fill-pattern': 'solid',
          'fo:font-family':
            "'Montserrat','NeverMind','Microsoft YaHei','PingFang SC','Microsoft JhengHei','sans-serif',sans-serif",
          'fo:font-style': 'normal',
          'fo:font-weight': 500,
          'fo:font-size': '14pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'center',
        },
      },
      summary: {
        id: '7e7d8704-9339-4a37-a8dc-f3a3aa2f4cf2',
        properties: {
          'line-color': '#a3a3a3',
          'shape-class': 'org.xmind.summaryShape.round',
          'line-width': '2pt',
          'line-pattern': 'solid',
          'line-corner': '8pt',
        },
      },
      relationship: {
        id: '81c8d0be-6082-4a1c-b88c-23b1445e0647',
        properties: {
          'line-color': '#a3a3a3',
          'shape-class': 'org.xmind.relationshipShape.curved',
          'line-width': '2',
          'line-pattern': 'dash',
          'arrow-begin-class': 'org.xmind.arrowShape.none',
          'arrow-end-class': 'org.xmind.arrowShape.triangle',
          'fo:font-family':
            "'Montserrat','NeverMind','Microsoft YaHei','PingFang SC','Microsoft JhengHei','sans-serif',sans-serif",
          'fo:font-style': 'normal',
          'fo:font-weight': 500,
          'fo:font-size': '13pt',
          'fo:text-transform': 'manual',
          'fo:text-decoration': 'none',
          'fo:text-align': 'center',
        },
      },
      map: {
        id: 'ea5bbe08-7b7a-4b13-a4ee-49b20dcc4de2',
        properties: {
          'svg:fill': '#ffffff',
          'multi-line-colors': '',
          'color-list': '#ffffff #232323',
          'line-tapered': 'none',
        },
      },
      importantTopic: {
        id: '6c4e5a0a-db82-4dc6-9816-213ad1a38238',
        properties: {
          'svg:fill': '#d02f48',
          'fill-pattern': 'solid',
          'border-line-color': '#232323',
        },
      },
      minorTopic: {
        id: 'febf0c47-d75e-4149-a07f-a44cf847e7ab',
        properties: {
          'svg:fill': '#f49d00',
          'fill-pattern': 'solid',
          'border-line-color': '#f49d00',
        },
      },
      colorThemeId: '0df8cd54-91cd-4160-9747-229e0171d358',
      expiredTopic: {
        id: '1ca15442-82a6-40f3-8664-b15fbdbb274b',
        properties: {
          'fo:text-decoration': 'line-through',
          'svg:fill': 'none',
        },
      },
      global: {
        id: 'e480bb4a-877f-41ce-9b0b-b01916f7deb7',
        properties: {},
      },
      skeletonThemeId: '42c88f12129a77f5482a880df3',
    },
    topicPositioning: 'fixed',
    coreVersion: '2.54.0',
  },
]
